import type { Metadata } from "next";
import { Poppins, Epilogue } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/providers/AuthProviders";
const poppins = Poppins({ subsets: ["latin"], weight: ["400", "700", "900"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className}`}>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
